# Generated by Django 4.1 on 2022-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='VEND_CODE',
            field=models.IntegerField(null=True, verbose_name='VEND_CODE'),
        ),
    ]
