# Generated by Django 4.1 on 2022-09-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0003_alter_order_ms_vchr_xo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_ms_vchr_xo',
            name='VEND_CODE',
            field=models.IntegerField(null=True, verbose_name='VEND_CODE'),
        ),
    ]
