# Generated by Django 4.1 on 2022-09-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0004_alter_order_ms_vchr_xo_vend_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_no',
            field=models.BigIntegerField(unique=True, verbose_name='T_No'),
        ),
    ]
