# Generated by Django 4.1 on 2022-09-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0005_alter_transaction_t_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SALE_PRICE',
            field=models.CharField(blank=True, max_length=200, verbose_name='SALE_PRICE'),
        ),
    ]
