# Generated by Django 4.1 on 2022-09-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0006_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SALE_PRICE',
            field=models.CharField(max_length=200, null=True, verbose_name='SALE_PRICE'),
        ),
    ]
