# Generated by Django 4.1 on 2022-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PURCH_PRICE',
            field=models.CharField(max_length=200, null=True, verbose_name='PURCH_PRICE'),
        ),
    ]
