# Generated by Django 4.1 on 2022-09-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0008_alter_product_purch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='VEND_CODE',
            field=models.IntegerField(null=True, verbose_name='VEND_CODE'),
        ),
    ]
