# Generated by Django 4.1 on 2022-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanApp', '0009_alter_product_vend_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ARABIC_NAME',
            field=models.CharField(max_length=200, null=True, verbose_name='ARABIC_NAME'),
        ),
        migrations.AlterField(
            model_name='product',
            name='NO_OF_ITEMS',
            field=models.IntegerField(null=True, verbose_name='NO_OF_ITEMS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PACK_ID',
            field=models.IntegerField(null=True, verbose_name='PACK_ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='UNIT_DESC',
            field=models.CharField(max_length=200, null=True, verbose_name='UNIT_DESC'),
        ),
    ]
